In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arr_2d = np.array(my_matrix)

In [9]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
np.linspace(3,6,20)

array([3.        , 3.15789474, 3.31578947, 3.47368421, 3.63157895,
       3.78947368, 3.94736842, 4.10526316, 4.26315789, 4.42105263,
       4.57894737, 4.73684211, 4.89473684, 5.05263158, 5.21052632,
       5.36842105, 5.52631579, 5.68421053, 5.84210526, 6.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [23]:
np.random.rand(5)

array([0.71475052, 0.49278526, 0.57280131, 0.44044416, 0.9545832 ])

In [24]:
np.random.rand(5,5)

array([[0.29760608, 0.23575264, 0.48333155, 0.50372785, 0.63273172],
       [0.77754267, 0.24659507, 0.10194963, 0.76171904, 0.32522496],
       [0.73982395, 0.26266123, 0.9764332 , 0.81661609, 0.69293102],
       [0.18430939, 0.68666911, 0.19612669, 0.87931216, 0.42685277],
       [0.5010158 , 0.40335157, 0.61585522, 0.81788839, 0.76754095]])

In [27]:
np.random.rand(3,5)

array([[0.24798495, 0.07754703, 0.31680791, 0.78639368, 0.55533215],
       [0.03820558, 0.04066065, 0.26395911, 0.07677878, 0.84880506],
       [0.18619822, 0.27073864, 0.9340675 , 0.57896375, 0.51120441]])

In [32]:
np.random.randn(2)

array([ 1.97411185, -0.13946387])

In [33]:
np.random.randn(4,4)

array([[ 1.4860719 , -0.11087123,  1.54069063, -0.17182742],
       [-0.27295715, -1.02111734,  2.01728278,  0.73629597],
       [-0.13389595,  0.86607575,  2.13932408,  0.92994916],
       [ 0.84930414,  0.10217196, -1.13686027, -0.44478167]])

In [34]:
np.random.randint(1,100)

71

In [36]:
np.random.randint(1,100,10)

array([24, 17, 42, 28, 54, 86, 14, 36, 42, 13])

In [48]:
arr = np.arange(25)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ran_arr = np.random.randint(1,50,10)

In [52]:
ran_arr

array([ 6, 29, 39, 43, 24,  1, 13,  5, 49, 24])

In [53]:
ran_arr.max()

49

In [54]:
ran_arr.min()

1

In [55]:
ran_arr.argmax()

8

In [56]:
ran_arr.argmin()

5

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr.shape

(25,)

In [60]:
arr = arr.reshape(5,5)

In [61]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.shape

(5, 5)

In [63]:
arr.dtype

dtype('int32')