In [4]:
import numpy as np

                1D ARRAYS

In [5]:
arr = np.arange(11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[:4]

array([0, 1, 2, 3])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:6] = 55

In [12]:
arr

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10])

In [13]:
arr = np.arange(11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:] = 33

In [24]:
arr_copy

array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])




                            2D ARRAYS

In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[1][1]

25

In [32]:
arr_2d[2][2]

45

In [34]:
arr_2d[2][0]

35

In [35]:
arr_2d[1,1]

25

In [36]:
arr_2d[2,2]

45

In [37]:
arr_2d[2,0]

35

In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [41]:
arr_2d[:2,1:2]

array([[10],
       [25]])

In [42]:
arr_2d[1:,2:]

array([[30],
       [45]])


              CONDITIONAL OPERATOR INDEXING  &  BOOLEAN ARRAYS

In [43]:
arr = np.arange(11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bool_arr = arr > 5

In [46]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [48]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr>7]

array([ 8,  9, 10])

In [51]:
arr[arr<4]

array([0, 1, 2, 3])



                    2D ARRAY EXERCISE

In [52]:
arr_2d = np.arange(50).reshape(5,10)

In [53]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [55]:
arr_2d[2:4, 6:8]

array([[26, 27],
       [36, 37]])

In [57]:
arr_2d[2:, 5:]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [58]:
arr_2d[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [62]:
arr_2d[1:4, 5:6]

array([[15],
       [25],
       [35]])

In [63]:
arr_2d[4:, 3:6]

array([[43, 44, 45]])